# Generated by Django 4.1.7 on 2023-04-15 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='gender',
        ),
    ]
